version: '3.8'

services:
  nuxt-ds:
    image: ${IMAGE:-nuxt-pnpm:latest}
    container_name: ${SERVICE_NAME:-nuxt-ds}
    build:
      context: .
      dockerfile: Dockerfiles/${DOCKERFILE:-PNPM}.Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
      - "80:3000"
      - "6006:6006"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    working_dir: /app
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=${HOST:-0.0.0.0}
      - SKIP_UPDATE=${SKIP_UPDATE:-false}

volumes:
  node_modules:
